As previously stated, Kiosken issues with product availability.
Members of Online have additional possibilities outside Kiosken, although they are at competitive student associations.
To keep students pleased and maintain a good reputation, Online and Trikom must be better in terms of item availability. 

=== Method

The Double Diamond Design approach cite:[doubleDiamond]  was utilized to perform service innovation in an attempt to overcome the previously identified challenge.
The approach, which is similar to the more generic Open Innovation process, comprises four separate phases.
The relevant tools and methods provided by the Double Diamond Design process are detailed in the following paragraphs.
In particular, the phases _discover_, _define_, and _develop_ will be covered.

==== Discover
During the Discover phase, one specifies certain enterprise challenges.
We will look into various service innovations that can hopefully fix these issues later.
As stated in the introduction, there are some issues with the restocking process.
The following aspects can be improved: 

* The item's availability must be manually confirmed.
This is normally done at random by both committee members and ordinary Online members.
There is no set procedure for dealing with items that are out of stock, other than sending an email to Trikom or addressing it to a committee member.
When such a mail is sent, or the message passed on, no more information surfaces until the kiosk is restocked.
It is unknown when it will be completed or even if the notice is received.

* Trikom must prepare ahead of time in order to carry out a restock.
First and foremost, all items in Kiosken's shelves must be counted and date verified.
The items in storage must then be counted and the dates must be confirmed.
A shopping list must be created once the current supply is counted.
The quantity of each item required must be estimated depending on both popularity and storage availability.
A shopping session requires a lot of repetitive and manual labor.
There is no computer aid, therefore it is time-consuming and prone to human mistake.
In the worst-case scenario, purchasing too much of an item may result in it going bad and needing to be thrown out prior to sale owing to a lack of storage capacity.
This is not beneficial for the economy as a non-profit kiosk. 


==== Define




// |===
// | Expectations |Theory related

// | Describe a service-oriented approach to your enterprise, with one or a few 
// services. (Innovation)

// | How would your enterprise remain agile and innovate? Describe the service 
// idea and how this could innovate your enterprise. Describe the type of 
// innovation w.r.t. the theory; e.g. open or closed innovation, digital, process, 
// etc. Reflect on the type of innovation(s), e.g. is this a service innovation, 
// process, digital or a business innovation? What is the ICT or digital component 
// of the innovation?

// |===

