=== Case Description

The selected case and its focus will be on the student association, Online cite:[LinjeforeningenOnline]. 
Online is one of the most significant student associations at NTNU, with nearly a thousand active members. 
Hierarchically, Online is built up by several committees, some larger than others. 
Out of the nearly thousand active members, at least 160 of them are committee members powering Online. 

The case will specifically target a process in one of the committees - Trikom cite:[trikom]. 
Trikom is the committee for well-being.
The committee is in charge of the kiosk at Online's office and organizes smaller social events, to mention some.

'''

The case itself regards the kiosk, hereafter called 'Kiosken.' 
Kiosken has a relatively broad selection of both snacks and soft drinks. 
Students purchase these items through an internal economy connected to the student ID cards.

Students would like to have all items available at all times. 
However, through some research and personal experiences, it is clear that the availability of items is unpredictable. 
For example, students experience empty shelves of their favorite snacks for an extensive period, and there is no
way of knowing when a restock happens.

As for the committee members of Trikom, there are several annoyances as well.
The restocking process appears to be quite comprehensive and unpredictable.
'When will it happen,' 'who is responsible,' and 'who does what' are frequently asked questions. 
Further, it appears to be much micromanagement which in an ideal world would not exist.

As a member of Online, I am a frequent user of Kiosken. 
The problems mentioned above significantly impact me as a regular customer. 
My biggest motivation for the presented case is to figure out how to streamline the restocking process and thus provide better and more predictable availability of the goods in Kiosken. 

By utilizing an enterprise model, from Trikom's perspective, one can hopefully understand the underlying processes of the restocking and identify innovations to streamline those.

<<<

[[processes]]
=== Case Processes

The overall process of keeping Kiosken restocked, is a combination of several smaller processes. 
The following paragraphs are meant to give a brief introduction to these.

*The Process of Identifying a Need For a Restock*

As of now, there is no concrete process of identifying the need for a restock. 
The need is identified by regular users reporting a lack of items, or by Trikom members checking manually. 
Even though regular users report few items, or they are identified as out of stock by Trikom themselves, the actually restock may not happen immediately. 
It is a common practice to wait for Kiosken to be almost out of stock of all items before a restock is even planned. 


*The Process of Planning a Restock*

When a restock is about to happen, a shopping list is to be made.
All items in Kiosken is counted, and how much of each should be bought is calculated.
A part of the planning is also to check the dates of existing items, as well as checking the storage room for space for the new ones.
When the storage is checked, and the shopping list is made, the Trikom members have to coordinate the shopping trip.
Assigning different tasks to different Trikom members, varying from driving and shopping, to carrying and filling shelves and storage.


*The Process of Restocking*

A car has to be rented and several members have to perform the actual shopping.
The shopping is done at a partner.
When the shopping is finished, either the same members as those who shopped, or others, have to carry all the new items into the storage unit and restock the shelves. 

Once the entire restocking process is initiated, it is time consuming and involves many parts. 
Ideally certain sub processes can be be improved or even eliminated by innovation.




// |===
// | Expectations |Theory related

// | A good textual description of the case that you will model and your 
// motivations for selecting this case and modelling. Are there any challenges 
// you want to address? Is there something you want to clarify?

// | If the description is inadequate, unclear or incomplete, marks will be 
// deducted.

// |===


// Kontekst, hvem er organisasjonen, hvem er du i den, relasjon
// Hva driver organisasjonen med?
// Hvorfor valgtes casen?

// Prosessen
// Hvilket perspektiv har casen? Ser den fra et Trikom-perspektiv
// Si hva casen dreier seg om
// Gå gjennom prosessene med ord og illustrasjon
