=== Purpose 

Kiosken is not generating any income for Online. 
Most business constantly aim to increase their profit.
However, the operation of Kiosken is a zero-profit project for Online.
Better availability will not generate more revenue, but the user satisfaction will greatly increase, which is in line with Trikoms goals. 

This model should serve as a beneficial overview of the key processes of the restocking of Kiosken. 
The current models give a precise overview of the relevant parts of the case AS IS.
No unnecessary information will surface, and the models have a logical easy-to-follow structure.
By getting a overview of all sub process, actors and goaals, Trikom could identify steps and processes that could be greatly improved. 
Through this, innovation can be applied, and Trikom optimize their processes, thus resulting in a better service for Onlines members.

==== Goals

There are many reasons to create enterprise models. 

[quote, Sandkuhl et al.]
A model is a generalized representation of a piece of reality, with only relevant real‐world properties taken into account during modeling. cite:[Sandkuhl_Stirna_Persson_Wißotzki_2014]

In other words, models help to represent and understand how an enterprise works. 
The models represent a relevant piece of reality, aiming to give greater insight into information, functions, behaviour and further on.

In this case, the models will as mentioned be used to analyze the business processes. 
To be precise, some sub goals will be *identifying possible innovation(s)* and *identifying potential threats to reaching the business goals*.
Among the goals of the model, its *ability to visualize* the processes to give better understanding, is among the most important ones.


// |===
// | Expectations |Theory related

// | Why are you modeling? How would the model address your case? What 
// purpose would your model serve? Note: this is very important for evaluating 
// the model as your model should be evaluated against this.

// | This must be very clear and well scoped. Sub-goals are also important. (Note: 
// goals of the model, not the enterprise you're modelling.) What are the success 
// criteria for your model? How would you know if/when the purpose of the 
// model is fulfilled - connection to evaluation of the model? Who wil be the 
// main users and beneficiaries of the model?

// |===


// Dra inn teori fra Vernadat her. Skriv om hvorfor man lager modeller
// Overfør til egen oppgave hvorfor det er relevant

// Hvem skal bruke modellen og hvordan?

// Sett opp goals og subgoals


// !! EM for finding change
// !! EM for process improvement
// EM for aligning business and IT
// EM for developing the strategic level of an IT-strategy


// Suksesskriterier
// Forståelig
// Presis
// Reell visualisering av business


// Relevante slides:
// Lecture 1 - Introduction to EM