[[purpose]]
=== Purpose 

Most business constantly aim to increase their profit.
However, the operation of Kiosken is a zero-profit project for Online.
Better availability will not generate more revenue, but the user satisfaction will greatly increase, which is in line with Trikoms goals. 

This model should serve as a beneficial overview of the key processes of the restocking of Kiosken. 
No unnecessary information will surface, and the models have a logical easy-to-follow structure.
By getting an overview of all sub process, actors and goals, Trikom could identify steps and processes that could be greatly improved. 
Through this, innovation can be applied, and Trikom optimize their processes, thus resulting in a better service for Onlines members.

[[goals]]
==== Goals

There are many reasons to create enterprise models. 

[quote, Sandkuhl et al.]
A model is a generalized representation of a piece of reality, with only relevant real‐world properties taken into account during modeling. cite:[Sandkuhl_Stirna_Persson_Wißotzki_2014]

In other words, models help to represent and understand how an enterprise works. 
The model represent a relevant piece of reality, aiming to give greater insight into information, functions, behaviour and further on.

In this case, the overall goal of the model is to be *_beneficial to analyze the business processes_*.
Some sub-goals will be to *identify possible innovation(s)* and *identify potential threats to reaching the business goals*.
Further, a goal is to *_visualize_* the business processes to get a hands-on look at what is actually going on.
Related to the vizualization-goal, a precise sub-goal will be to *create the model in such a way that the committe members of Trikom is able to utilize it*.

[[success_criteria]]
==== Success criteria

There are several ways to evaluate models. 
For instance, Sandkuhl et al. cite:[Sandkuhl_Stirna_Persson_Wißotzki_2014] mentions competency questions and quality criteria. One can also apply a framework such as SEQUAL. 
Common to all, is to evaluate how well the model fulfills its purpose.
For this case I will use the **quality criteria**.

There are many possible quality criteria one can apply. 
The criterias fitting the case the best are the following:

* **Usability** (Goal 1): The ease with which the enterprise model can be used for its intended
purpose cite:[Sandkuhl_Stirna_Persson_Wißotzki_2014].

** The model should be able to identify possible innovation(s). 
To achieve such, it has to include enough information with relevant details and perspectives/views. The goal is not met if the model is designed in a way that does not provide sufficient perspectives to analyze for possible innovation(s).

** If Trikom is unable to identify potential risks, the model is not adequate enough. 


* **Understanding** (Goal 2): The ease with which the concepts and structures in the enterprise
model can be understood by the stakeholders cite:[Sandkuhl_Stirna_Persson_Wißotzki_2014].

** The models have to be precise and understandable. Only the relevant information should be provided, and it should be in such a way that the Trikom committee members can make use of it. 

** The criteria is not met if the model leads to uncertainties and confusion, i.e regarding processes or involved actors.



// |===
// | Expectations |Theory related

// | Why are you modeling? How would the model address your case? What 
// purpose would your model serve? Note: this is very important for evaluating 
// the model as your model should be evaluated against this.

// | This must be very clear and well scoped. Sub-goals are also important. (Note: 
// goals of the model, not the enterprise you're modelling.) What are the success 
// criteria for your model? How would you know if/when the purpose of the 
// model is fulfilled - connection to evaluation of the model? Who wil be the 
// main users and beneficiaries of the model?

// |===


// Dra inn teori fra Vernadat her. Skriv om hvorfor man lager modeller
// Overfør til egen oppgave hvorfor det er relevant

// Hvem skal bruke modellen og hvordan?

// Sett opp goals og subgoals


// !! EM for finding change
// !! EM for process improvement
// EM for aligning business and IT
// EM for developing the strategic level of an IT-strategy


// Suksesskriterier
// Forståelig
// Presis
// Reell visualisering av business


// Relevante slides:
// Lecture 1 - Introduction to EM