[[model_design]]
=== Model Design

The enterprise models presented are mostly concerned with the business process.
By concentrating on the business process, one may see both the important procedures and the individuals involved.
The goals are also significant since they serve as the reason why the tasks are carried out.

To begin developing the models, I concentrated on the processes.
It was critical to have a thorough grasp of how a Kiosken operates.
When the processes with it's sub processes was modeled, I focused on the goals.
To begin, I had some rough thoughts about the goals, but when the processes was clear, the goals were concretized and split into sub-goals. 

Once the processes were identified, the actors manifested themselves intuitively.
To avoid extraneous information, the models incorporate just relevant actors. 
One may question why the actors are included when there is only one actor performing the actual tasks in the first models. 
The reason is to acknowledge the existence Dotkom, as they bring the opportunity to create the proposed service. 
In the latter models, the actors include the very important developers both creating and maintaining the service.

The enterprise model was created using a top-down method.
The goals are provided first, followed by the procedures and the essential actors.
The model's user is supposed to first comprehend the goals, then what is currently happening and what may be improved. 

Both 4EM and ArchiMate employ comparable perspectives in this case.
The perspectives chosen were the most appropriate for the model and situation.
Because we were only going to use one modeling language for the report, having similar models aided us in deciding on a language. 



// |===
// | Expectations |Theory related

// | This section should explain the design decisions and how you have designed 
// your model to meet its purpose.

// | How have you structured your model to reflect your case and the purpose? 
// How does the choice of the enterprise aspects reflect your case?  

// |===

// Forklar modellene, screenshots av alle
// Ta dem hver for seg og som enterprisemodeller

// Husk archimate og 4em, forskjellige views mm. 
// Dette er before views 

// Det beskrives hvilke tools som brukes og hvorfor man går videre med tool x

