=== Model Evaluation
In this section I will evaluate the models created. In xref:goals[] I described the goals, sub-goals and purpose as the following:

. The model should *be beneficial to analyze the business processes*

.. It should be able to *identify possible innovation(s)*

.. 1.2 It should *identify potential threats to reach the business goals*

. The model should overall *visualize*

.. It should be *created in such a way that the committe members of Trikom is able to utilize it*

To evaluate the models I will use *quality criteria*. 
*Quality criteria* are utilized because, while it focuses on the models and how accurate they are in terms of modeling the business, it allows for subjective quality. 
I.e it covers the models usability and understanding, which are very important parts for those going to utilize them.

According to Krogstie et al., 'what quality criteria are relevant and how strictly they are to be followed depends on the purpose of modeling or goals of modeling' cite:[krogstie], and this is taken into consideration for this section. 
The criterias *simplicity* and *integration* is omitted as own paragraphs as they are covered sufficiently in the other criterias.

NOTE: All definitions in the following paragraphs are by Sandkuhl et al. cite:[Sandkuhl_Stirna_Persson_Wißotzki_2014]

*Usability*

_The ease with which the enterprise model can be used for its intended purpose._ 

The models were designed to be useful in analysing business processes.
It has shown to be useful in identifying a potential innovation, namely the Stock Tracker service.
It also covers potential threats that stakeholders / intended users should be aware of. 
Its design is straightforward, and the Trikom committee members should be able to use it.
The proposed service innovation should have a clear impact on the existing business process and it covers the required changes to achieve so.

The _usability_ of the model is evaluated very good.


*Understanding*

_The ease with which the concepts and structures in the enterprise model can be understood by the stakeholders._

It is worth emphasizing that the stakeholders that use this model will be quite familiar with all of the existing Kiosken-processes.
Because I was aware of this during the modeling process, I may have been less detailed than I would have been if the users were less familiar.
This is compensated for by textual descriptions.

Certain arrows in the Enterprise Model are a little difficult to follow.
They are quite lengthy and have several pathways.
Textual descriptions compensate for this as well. 

The _understanding_ of the model is evaluated good. 


*Completeness*

_The degree to which all relevant facts of the problem domain are included in the enterprise model._

The case considers a specific process, namely the restocking of Kiosken. 
All sub-processes and models included are related to this. The goals are realized by the processes and the proposed service. The actors presented are either performing actions related to the overall process, or essential to the Stock Tracker. 

The _completeness_ of the model is evaluated very good.

*Correctness*

_How well the enterprise model conforms to the rules of the modeling technique._

In my case, the modeling technique of choice was 4EM.
This criterion assesses how effectively my model adheres to the language's scope and makes use of the language's current syntax and rules.


The model adheres to the syntax and rules of the language.
I may have overlooked certain elements of the language that would have made modeling easier, but the finished product should meet expectations. 

The _correctness_ of the model is evaluated good.

*Flexibility*

_The ease with which the enterprise model can cope with changes in the modeling domain._

Everything was created using https://draw.io[draw.io].
Within the tool, the various sub-models are separated into their own tabs, making it simple to make modifications to only certain components.
As a consequence of the multiple sub-models being separate, the model is particularly adaptable and robust to dealing with changes within the domain.
Furthermore, because the model is not very complicated, the amount of work required to make necessary adjustments would be manageable. 

The _flexibility_ of the model is evaluated very good.



// |===
// | Expectations |Theory related

// | Assess if your model meets its purpose. You can use any of the methods we 
// learned for evaluating models or any other means. (Hint . connect your 
// model to its purposes and ask if it meets the purpose

// | How did you evaluate yur model . what evaluations methods (from theory) did 
// you consider? Justify your choice of evaluation method(s). Describe how you 
// evaluate your model, using the model and include screen shots of the relevant 
// parts of the model. Describe why you think your model is good and meets the 
// purpose (or not). 

// |===