=== Reflections

I found the entire process to be rather challenging.
I haven't been able to attend as many lectures as I had anticipated, but I've done my best to stay up-to-date through available learning materials and engagement with fellow students.
The main issue was connected to many big words and definitions I was not familiar with, and at some point had misunderstood.
Fortunately, this was mostly resolved during exercise lessons in which I believe i greatly benefited from.

It was a lot of fun brainstorming potential cases.
I took on one case very early, and worked on it extensively until I concluded it just would not work.
Starting from scratch with a new case was definitely discouraging, but I had learned a lot and the process went much more smoothly the second time.
The largest advantage was taking detailed notes and describing the case thoroughly before modeling.

I'm glad I have some prior experience with information systems and modeling.
Modeling my case was challenging using new tools, but it got exciting after I got the hang of it and the many elements fell into place.
It took several modeling iterations until I was satisfied, and I am pleased with the outcome.

If I had to do it all over again, I would surely do certains things differently.
Before modeling, I would familiarize myself with both 4EM and ArchiMate so that I could have a better modeling experience.
Even while it was exciting at times, I spent a lot of time overwhelmed and confused by conventions and syntax.
I would also consider getting familiar with more of the frameworks for evaluation and enterprise architectures. 

All in all i think it was a challenging process, but I feel I have gotten rather good insights into business and enterprise modelling, as well as service innovation and the methods for analyzing them cite:[CourseEnterpriseArchitecture].

As I've never written anything longer than a few pages, writing such an extensive report was a great learning experience as well.

// |===
// | Expectations |Theory related

// | Describe what you have done. Reflections and lessons learned. Reflect on 
// the work, the process you followed and share some of your thoughts.

// | Also discuss the modelling experience. And what would you do anything 
// different next time? 

// |===

