=== Reflections

I found the entire process to be rather challenging.
I haven't been able to attend as many lectures as I had anticipated, but I've done my best to stay up-to-date through available learning materials and engagement with fellow students.
The main issue was connected to many big words and definitions I was not familiar with, and at some point had misunderstood.
Fortunately, this was mostly resolved during exercise lessons.

It was a lot of fun brainstorming potential cases.
I took one case early on, and worked on it extensively until I concluded it just would not work.
Starting from scratch with a new case was a little discouraging, but I had learned a lot and the process went much more smoothly the second time.
The largest advantage was taking detailed notes and describing the case thoroughly before modeling.


I'm glad I have some prior experience with information systems and modeling.
Modeling my case was challenging using new tools, but it became fun after I got the hang of it and the many elements fell into place.
It took several modeling iterations until I was satisfied, and I am pleased with the outcome.

If I had to do it all over again, I would surely do certains things differently.
Before modeling, I would familiarize myself with both 4EM and ArchiMate so that I could have a better modeling experience.
Even while it was fascinating at times, I spent a lot of time overwhelmed and confused by conventions and syntax.
I would also consider getting familiar with more of the frameworks for evaluation and enterprise architectures. 

All in all i think it was a challenging process, but I feel I have gotten rather good insights into business and enterprise modelling, as well as service innovation and the methods for analyzing them.

// |===
// | Expectations |Theory related

// | Describe what you have done. Reflections and lessons learned. Reflect on 
// the work, the process you followed and share some of your thoughts.

// | Also discuss the modelling experience. And what would you do anything 
// different next time? 

// |===









// I found the entire process quite difficult. I have not attended as many lectures as I hoped for, but I've tried my best to keep up to date through the posted learning material and collaboration with fellow students. The main issue was connected to many big words and definitions I was not familiar with, and at some point had misunderstood. This was luckily solved for the most part during exercise lectures.

// Brainstorming the potential cases was very exciting. I chose one case very early and did a significant amount of work on that, until i realized it just would not work. Starting from scratch with a new case was a bit demotivating, however, I had learned a lot and the second time the process went much smoother. The greatest benefit was taking notes and describing the case thoroughly before modeling. 

// I am very happy that I was a bit familiar with information systems and modeling from earlier. Modeling my case was difficult with new tools, however it became exciting once I got the hang of it, and the different pieces came in place. It took many iterations with modeling until I was satisfied, and I am happy with the results. 

// I would definitely do certain things different if I was to do the process all over. I would make myself more familiar with both 4EM and ArchiMate, before modeling, so I could have a better modeling experience. Even though it was exciting at times, I spent a significant amount of time being frustrated and confused with conventions and syntax. I would also consider getting familiar with more of the frameworks for evaluation and enterprise architectures. 

// All in all i think it was a challenging process, but I feel I have gotten rather good theoretical insights into business and enterprise modelling, as well as service innovation and the methods for analysing them.