/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExpenseTracker;

import java.io.File;
import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        File myFile = new File("./testing.txt");
        ExpenseManager manager = new ExpenseManager();

        try (Scanner sc = new Scanner(System.in)) {
            String input = sc.next();

            while (input != "0") {
                System.out.println();
            }
        } 

    }
}
