/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExpenseTracker;

import java.io.File;

public class App {
  public static void main(String[] args) {
    File myFile = new File("./testing.txt");
    ExpenseManager manager = new ExpenseManager();
    
    // TODO: Make menu system and CLI
    String menu = new StringBuilder()
      .append("Welcome to the Expense Tracker!\n")
      .append("1 - Add expense\n")
      .append("2 - List expenses\n")
      .append("\n")
      .append("0 - Quit")
      .toString();
    
    manager.readFile(myFile);
    System.out.println(manager.showData());
  }
}
