[[business_initiative]]
== Business Initiative

Voi Technology is the fastest-growing European micro-mobility provider. 
The Scandinavian company offers electric scooters in collaboration and partnership with local communities around Europe cite:[RideVOIFuture]. 
Voi envisions cities free from congestion, noise, and pollution. 
To accomplish this, Voi takes advanced technologies and makes them accessible to everyone.
As a user, one should get from point A to point B in time, total silence, and free from fossil fuels cite:[VoiTechnologyShaping]. 

Voi is the fastest-growing European micro-service provider, but they are also the first European scooter operator. 
Founded in 2018, the company has had tremendous growth, and as of 2021, they have over six million users. 
What started as a small startup born in Sweden has become an international company with over five hundred employees from over fifty nationalities. 

Voi does not publicly publish annual reports detailing previous years' financial results or future strategic plans.
However, Voi has published several reports regarding security and sustainability.
Based on the publicly provided information cite:[SafetyPledge, Sustainability] and assumptions, one can create a list of important key performance indicators (KPI). 
Using these KPIs, one can gauge the company's progress.

.Key Performance Indicators
[cols="^1,8"]
|===
2+|Key Performance Indicators (KPI)

|1 | Increase annual recurring revenue

|2 | Extend vehicle lifespan

|3 | Reduce micro-mobility accidents
|===


The focus initiative of this report and the target business initiative will be increasing the annual recurring revenue by 5% by the end of 2022. 
Voi is in a growth phase, and the initiative is essential to provide better solutions and products and prove to shareholders that their business model is viable. 
The revenue stream encompasses revenue from a variety of scooter subscriptions and single trips.

Further, Voi pursues and advocates for a zero-vision of micro-mobility accidents and being climate neutral cite:[SafetyPledge, Sustainability]. 
Voi intends to take responsibility for its environmental impact and the user's safety.
The micro-mobility sector is brand new, and as first-movers, Voi has a crystal clear action plan to improve their climate impact and leave a well-leading trail for aftercomers. 