[[business_initiative]]
== Business Initiative

Voi Technology is the fastest-growing European micro-mobility provider. 
The Scandinavian company offers electric scooters in collaboration and partnership with local communities around Europe cite:[RideVOIFuture]. 
Voi envisions cities free from congestion, noise, and pollution. 
To accomplish this, Voi takes advanced technologies and makes them accessible to everyone.
As a user, one should get from point A to point B in time, total silence, and free from fossil fuels cite:[VoiTechnologyShaping]. 

Voi is the fastest-growing European micro-service provider, but they are also the first European scooter operator. 
Founded in 2018, the company has had tremendous growth, and as of 2021, they have over six million users. 
What started as a small startup born in Sweden has become an international company with over five hundred employees from over fifty nationalities. 

Voi intends to take responsibility for its environmental impact.
The micro-mobility sector is brand new, and as first-movers, Voi has a crystal clear action plan to improve their climate impact and leave a well-leading trail for aftercomers. 


- øke antallet kunder
- færre skadde
- lengre levetid på scooterne






In this section you will need to describe the organization you have selected and present some information about its main activities, its history and operations, as well as how it has been operating in the last years. 

After this brief introduction you will identify a target business initiative and describe it in a bit more depth (what it includes, why it is important for the organization, what is its time-frame etc)

Note: 
The business initiative can be something broad enough so that it can be decomposed later into several use cases.

- beskriv voi
	- antall ansatte
	- omsetning
	- kort om bakgrunn
	- noe om hvordan det har vokst?


- noe om at det var vanskelig å definere spesifikke KPIier, men at man basert på egen forståelse kan definere selv
	- sikkerhet
	- kvalitet
	- få flere til å ta trafikkskolen
	- spredning til flere land og byer (krever da samarbeid med myndighetene)
	- flere brukere

- husk å sette dato