[[changes]]
=== Changes in the Enterprise Model

The models will be redesigned in this section to complement the planned innovation.
Changes will be made to the 4EM-models.
The affected models are both the Actors and Resources Model and the Business Process Model. 
Naturally this affects the Enterprise Model as well.
All notable changes in the models are highlighted with red borders (does not include constraints in Goal model).

[[changed_actors_text]]
==== The Changed Actors and Resources Model

This model has been updated to include the developers from Dotkom. 
The developers play a significant role in both the creation of the proposed service as well as its maintenance. 


[[changed_actors]]
.The Actors and Resources Model || 4EM
image::figures/TOBE/changed_actors.svg[align='center']

==== The Changed Business Process Model

The most significant change appears in this model. 
The first process is totally eliminated, and the new process starts with the old process' output, namely _Information set 2 - Shopping list_. 
In line with the goals defined in xref:em_goal[the Goal model], the proposed service has streamlined certain parts of the restocking process. 
Previously the shopping list was created manually, and the need for a restock uncovered in the same manual way. 

The notification,  _Information set 1, remains the same, however the way it is created is new. 
This is not shown in the model, but described in this paragraph and previously. 
The proposed service, the Stock Tracker, keeps track of the items in stock. 
When a certain threshold is reached, it sends a notification to Trikom with a tailored shopping list.

A Slack-notice (_Information set 3_) is issued as a new element in _Process 1_.
This tells all of Online's members that a restock is in the works.
As a result, the stock is more predictable, which motivates the goal of enhanced customer satisfaction. 

A new information set is shown in _Process 2_.
This information set offers data about the current stock following the restock.
This data is added to the Stock Tracker to keep it up to date.
When this is accomplished, a notification is issued to all of Online's members informing them that Kiosken's items are once again available. 

[.landscape]
<<<
[[changed_process]]
.Changed Business Process Model || 4EM
image::figures/TOBE/changed_process.svg[scaledwidth=90%, align='center']
[.portrait]
<<<

==== The Changed Enterprise Model

The modified Enterprise Model is depicted in xref:changed_em[].
The components have been reorganized in order to improve readability.

The goals' arrows have been revised to point to more specific areas of the processes, making it clearer how the innovation affects them.
The same is applicable for the Trikom members' roles and interactions.
xref:changed_actors_text[] highlighted the modifications for Dotkoms developers and their involvement in the maintenance of the Stock Tracker.

The revised model should be easier to grasp, and provide a more natural picture of the overall business and its processes, relevant to the case. 

[.landscape]
<<<
[[changed_em]]
.Changed Enterprise Model || 4EM
image::figures/TOBE/changed_em.svg[scaledwidth=120%, align='center']
[.portrait]
<<<

// |===
// | Expectations |Theory related

// | Identify the changes that you have to make in your enterprise to realise the 
// business model and deliver the services. Enhance your 4EM or Archimate 
// model from part 1. The new model should be submitted. (Hint: did the 
// service innovation create more goals for your enterprise? If so, are there 
// implications for the processes, roles, technology, etc. in your enterprise?)

// | Explain the changes in your enterprise model and how they would support the service innovation e.g. new or changed processes, new organisational 
// structure, new competences and therefore new roles and actors, perhaps new 
// technological solutions, etc.). Note: again, it's important to be clear about the 
// purpose of the model as was relevant for part 1.

// |===